name: Azure Media Manager CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      env:
        REACT_APP_POST_URL: ${{ secrets.REACT_APP_POST_URL }}
        REACT_APP_GET_URL: ${{ secrets.REACT_APP_GET_URL }}
        REACT_APP_PUT_URL: ${{ secrets.REACT_APP_PUT_URL }}
        REACT_APP_DELETE_URL: ${{ secrets.REACT_APP_DELETE_URL }}
        REACT_APP_APPINSIGHTS_CONNECTION_STRING: ${{ secrets.REACT_APP_APPINSIGHTS_CONNECTION_STRING }}
        
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: react-app
        path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: react-app
        path: build
        
    - name: Deploy to Azure Static Web App
      id: deploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "build"
        api_location: ""
        output_location: ""